version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: Lou
      POSTGRES_PASSWORD: Gonch
      POSTGRES_DB: onlypetsdb

  onlyPets:
    image: lougonch/onlypets2:latest
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: Lou
      POSTGRES_PASSWORD: Gonch
      SECRET_KEY: itsasecret
      DATABASE_URL: postgresql://Lou:Gonch@postgres:5432/onlypetsdb
    depends_on:
      - postgres